# Generated by Django 4.2.5 on 2023-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(default='GIFT100', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(default='100 TL discount for all products !', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.FloatField(),
        ),
    ]
