# Generated by Django 4.2.5 on 2023-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_offer_code_offer_description_alter_offer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(default='deneme', max_length=20),
        ),
    ]
